### ISSUE TITLE
This module might be a lie...

### ISSUE THREAD

**Issue by coolaj86** [coolaj86/node-ssl-root-cas#17]
I just discovered that the most common reason you would have the kind of problems this module solves is actually due to failing to properly bundle the Intermediate CAs with the server certificate.

**Comment by tgourley01** [comment]
IMO poor server config does not make this project a lie. Adding trusted certs is a common problem. Nodejs made this a hard problem and this project helps. In my case we have server certs signed by an untrusted signer and this project helped. Thanks for sharing this project.

**Comment by coolaj86** [comment]
Well said.

:)
