### ISSUE TITLE
How do I set it up behind a proxy server

### ISSUE THREAD

**Issue by mithun-daa** [coolaj86/node-ssl-root-cas#19]
My server is behind a squid proxy. I have whitelisted the mozilla url (https://mxr.mozilla.org/nss/source/lib/ckfw/builtins/certdata.txt?raw=1) that the module tries to get to get the latest CAs but looks like it cannot reach it. I get the following error:

```Couldn't download the latest Root CAs, but it's not a big deal.
Use "require('ssl-root-cas')" instead of "require('ssl-root-cas/latest')"```

**Comment by coolaj86** [comment]
Here's a couple of options:
* Don't worry about it, just use the latest version and occasionally reinstall the new latest version
* Install it on a system with a full internet connection and then copy it over
