### ISSUE TITLE
global.Promise

### ISSUE THREAD

**Issue by Diokuz** [coolaj86/node-ssl-root-cas#20]
Can you change Promise polyfill, please? It overrides native promises in nodejs 4.x.

https://github.com/jakearchibald/es6-promise/issues/140

**Comment by igrayson** [comment]
Just hit this. This took a while to debug, and makes this library pretty dangerous for us (and others..)

**Comment by coolaj86** [comment]
Fixed in v1.1.11 and v1.2.0
