### ISSUE TITLE
add http-server example?

### ISSUE THREAD

**Issue by greggman** [coolaj86/node-ssl-root-cas#21]
Thank you so much for your example

I thought I'd point out that the `http-server` npm package will take certs from your instructions

      npm -g install http-server
      http-server --ssl --cert server/my-server.crt.pem --key server/my-server.key.pem 

I just needed https locally to test some stuff that browser block on http. Of course the browsers don't block localhost but if you're testing mobile the above will let you connect your mobile browser to `https://<ipaddress>:8080`.  Add in `-p 443` if you want the default https port (probably need to prefix with `sudo`)

**Comment by coolaj86** [comment]
Also check out `serve-https`, which defaults to https and can also take the same arguments above, and even load an express app.

**Comment by coolaj86** [comment]
Added here https://github.com/coolaj86/node-ssl-root-cas/commit/4f17d70e1a3139cbf6c0a1d76eb642ce434735d4
