### ISSUE TITLE
{"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE"}

### ISSUE THREAD

**Issue by prashathsenthil** [coolaj86/node-ssl-root-cas#22]
I'm getting this error "UNABLE_TO_VERIFY_LEAF_SIGNATURE" and googled and tried process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0'; and since this is a bad idea i thought of using ssl-root-cas module and added the below line in my code,

require('ssl-root-cas/latest').inject();

Even after adding this i get the same error.. Any reason why? I'm simply trying to post and retrieve data's to/from an end point on a node service code.

**Comment by prashathsenthil** [comment]
I'm still stuck with this issue, any help would be greatly appreciated.

**Comment by coolaj86** [comment]
Take a look at these two examples:

* https://github.com/coolaj86/nodejs-self-signed-certificate-example
* https://github.com/coolaj86/nodejs-ssl-example

If your company or organization uses their own self-signed root CA you'll need to add that using `addFile('/certs/our-root-ca.pem')`.
