### ISSUE TITLE
Mozilla CA file URL is down.

### ISSUE THREAD

**Issue by mikeflynn** [coolaj86/node-ssl-root-cas#24]
Just a heads up to anyone else who ran in to this problem but Mozilla has the CA page the code pulls the latest from in to a maintenance page. That would be fine, but the maintenance page returns a 200 status code so the HTML is being downloaded and used as the CA file.

I've submitted a pull request to check for the content type in addition to the status code which should prevent this issue in the future: https://github.com/coolaj86/node-ssl-root-cas/pull/23

**Comment by coolaj86** [comment]
Fixed in v1.1.11 and v1.2.0. Not closing yet though as a reminder to publish v1.2.20160621 with updated certs

**Comment by LoicAG** [comment]
Thanks for the fix!
I realise this is unrelated to this project, but does anyone know how long the URL will be down, or where to get information about it?

**Comment by coolaj86** [comment]
Closed with #25
