### ISSUE TITLE
Get latest fails with invalid content type

### ISSUE THREAD

**Issue by rlk833** [coolaj86/node-ssl-root-cas#25]
/latest uses:
https://mxr.mozilla.org/nss/source/lib/ckfw/builtins/certdata.txt?raw=1

This is now returning Content-Type of ' text/plain; charset="UTF-8" '

The code checks for only 'text/plan' and fails to use the latest.

I don't know if this is related to coolaj86/node-ssl-root-cas#24

**Comment by coolaj86** [comment]
@mikeflynn, I think this was introduced by your patch? Mind taking a look and, if so, making the change? Thanks!

**Comment by mikeflynn** [comment]
Yup, agreed. Glad to see Mozilla actually got the page back up so we can test it against the real page finally.

Patch coming...

**Comment by mikeflynn** [comment]
Just pushed this change to master: 3695778550e9f2f00fb1fbbfd2a612770b52c388

Switched check to `if (response.headers['content-type'].indexOf('text/plain') !== 0) {` which will allow for charsets but ensures text/plain is the first thing in the content type.

I just put it in to master, but I'll let @coolaj86 merge the change in to the various version branches and get it up to npm.

**Comment by coolaj86** [comment]
Thanks.

Published v1.2.1 with the fix and the latest certs.
