### ISSUE TITLE
HTTPS REQUEST- UNABLE TO VERIFY CERTIFICATE

### ISSUE THREAD

**Issue by 2Marks** [coolaj86/node-ssl-root-cas#26]
after adding the require('ssl-root-cas/latest').inject();
i still get the same error.

![git-https](https://cloud.githubusercontent.com/assets/12138334/16977734/ccc31dcc-4e4f-11e6-8d5b-49cf1b0bd45b.PNG)
any help appreciated.

**Comment by yswai** [comment]
Hi,

I am having the same problem as well.
Starfield G2

**Comment by coolaj86** [comment]
It looks like you're using a company-signed or self-signed CA, but you didn't add it.

You need to use `.addFile('/path/to/file')` to add your custom CA into the root chain.

If you need to see the certificate and save it to a file, this might help: https://www.tbs-certificates.co.uk/FAQ/en/247.html

(often the company-signed cert will include the root as well)

**Comment by 2Marks** [comment]
fixed it by adding rejectUnauthorized:false, to the api options using node https request.
![rejectunauthorized](https://cloud.githubusercontent.com/assets/12138334/19549742/f18f14ee-969d-11e6-9470-0b2713b56094.PNG)

**Comment by coolaj86** [comment]
`rejectUnauthorized` will disable the security verification of the request, defeating the purpose of the certificate.

The correct solution to this problem is the one I mention - you need to put the root certificate (and any intermediates) in the chain.

**Comment by coolaj86** [comment]
Correction: you don't add the intermediates. The intermediates must be bundled with the certificate being served by the webserver.

You can test to see if the configuration is an error on their end with:

```bash
openssl s_client -showcerts \
  -connect example.com:443 \
  -servername example.com
```

**Comment by 2Marks** [comment]
@coolaj86 the API i was using doesn't have the HTTPS signed. the API doesn't have an HTTPS certificate yet. just an embedded one.  i tried adding the root certificate but still it did not work. which i feel its because the API itself doesn't have a valid HTTPS signed certificate.
